### PR TITLE
vrj sign() function

### PR DESCRIPTION
**Pull request by damste**
Hi Rick,
sign function implemented
let me know

### CODE REVIEW

**Comment by RickCHodgin** [comment]
I'll go ahead and merge the pull, then refactor the sign output to match the variable type as input. There may also be an issue with dividing a number by itself in floating point ... sometimes a + b does not equal b + a in floating point values in IEEE754.

**Comment by RickCHodgin** [comment]
Excellent work, Stefano. :-) Thank you.

**Comment by damste** [comment]
I' m sorry that you should always rewrite my code, I hope to become more
productive with the passage of time

Il sabato 14 marzo 2015, Rick C. Hodgin <notifications@github.com> ha
scritto:

**Comment by RickCHodgin** [comment]
Don't even worry about it! :-)  I am *SO VERY THANKFUL* that you are 
contributing.  Even with the minor rework, which I know you will do in 
time by yourself, it saves me so much time.

It's far easier to debug than create. :-)  Keep up the fantastic work, 
Stefano.  Code at your own pace.  And know that everything you 
contribute is appreciated (not just by me, but by the others who will 
also be encouraged to help out).

Your contributions go far beyond source code.  They are the kind of 
thing which breaks through mental barriers.  It's going to be easier for 
other developers to join the "two who are coding" rather than the "one 
Rick religious guy who is coding". :-) LOL!

Anyway ... I can't tell you how happy I am. :-)

Best regards,
Rick C. Hodgin

**Comment by damste** [comment]
Hi Rick,
sign() function should always return an integer... What do you say?
...
		//////////
		// Create output variable
		//////
			//result = iVariable_create(thisCode, varNumber->varType, NULL);
                        result = iVariable_create(thisCode, _VAR_TYPE_S64, NULL);
			if (!result)
			{
				iError_reportByNumber(thisCode, errorNum, iVariable_compRelated(thisCode, varNumber), false);
				return(NULL);
			}
...
Now
? sign(3.0) && Display 1.00 instead of 1

Let me know

Best regards,
Stefano

**Comment by RickCHodgin** [comment]
Okay, here's my thought process:

Consider:  SIGN(xValue)   && xValue indicates could be nValue, or fValue for floating point

If it's nValue integer, the result will be integer.  If it's fValue floating point, the result will be floating point.  In this way it keeps the same form as the input.

My thinking is that the SIGN() value will be used in a calculation which in some way relates to the source input value, and rather than converting it to integer, and then back to floating point later, in the cases of fValue it will go ahead and leave it as floating point.

What do you think?  Is it sheer lunacy? :-)

**Comment by damste** [comment]
Your thinking is correct... I was referring to the fact that the sing()
always returns an integer in vfp. Must VJr be fully compatible with VFP or
not?

PS
However, I agree with you, your sign() function is better than that of vfp
:-)

2015-03-15 14:15 GMT+01:00 Rick C. Hodgin <notifications@github.com>:

**Comment by damste** [comment]
Another thing... following your reasoning, must SQRT() behave as the sign()?
Example:
? sqrt (2) && Display 1 instead of 1.41 ?
? sqrt (2.0) && Display 1.41

2015-03-15 14:47 GMT+01:00 Stefano D'Amico <damicoste@gmail.com>:

**Comment by RickCHodgin** [comment]
That's a good point... maybe we should introduce some new settings which address things like this.  It could be the NUANCECOMPATIBILITY() function, which sets specific nuances of compatibility.  It would work like SYS() in that it has an nIndex, and then a value after indicates its setting.

Example:  NUANCECOMPATIBILITY(1, ON)   && Sets the SIGN() function to be compatible, and always return an integer.

What do you think?

Keep in mind on this project ... we are in creator mode.  We are not constrained by what currently exists.  We can accommodate the existing, but also accommodate what should've been there, or what we would like to see.  The two are not incompatible, but can work together as we look forward to bigger and better things. :-)

Best regards,
Rick C. Hodgin

**Comment by RickCHodgin** [comment]
I would say SQRT() is always expected to be a floating point value.  So, it should always return floating point even if the input is an integer.

Best regards,
Rick C. Hodgin

**Comment by damste** [comment]
I would say that we should allow compatibility with the past so that we can
run our old prg without too many changes.
The idea of setting seems to me the best...

And sqrt() always returns floating point value for me too

2015-03-15 16:23 GMT+01:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
Okay.  I'll add the nuancecompatibility() settings function, which I'll call ncset() for short. :-)

Best regards,
Rick C. Hodgin

**Comment by damste** [comment]
I thought ... I could implement numeric functions with a unique internal
function (with switch case)
EXP(), SQRT(), LOG(), LOG10(), etc ... have all the usual structure:

1. test for numeric parameter
2. converting to F64
3. computing
4. result as float

what do you think?

2015-03-15 16:23 GMT+01:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
Excellent. :-)  I do something similar with occurs(), trim(), etc.

Best regards,
Rick C. Hodgin

**Comment by RickCHodgin** [comment]
I refactored sign() and added sign2().  They use a common function now so you can see how that works. :-)

https://github.com/RickCHodgin/libsf/commit/fa764424ed1c8d8ec54a2fffc63c1c30f2867709

**Comment by damste** [comment]
to be honest I was almost done :-P
I will look your example

2015-03-15 18:39 GMT+01:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
OH!!!  I didn'tk now you were doing it there.  I'll look at yours.  I can remove the commit from GitHub if you like.

**Comment by damste** [comment]
i am doing common numeric function for exp,sqrt,pi,log,log10
no sign() :-)

2015-03-15 18:42 GMT+01:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
Okay great!  You can see the common implementation for sign() and sign2().  Whew!  I thought I double-did your work.

Looking forward to it.  VJr development is moving forward at warp speed these past days.  So exciting.

**Comment by RickCHodgin** [comment]
I found a bug in mine.  It should be "else if (tlIncrement0)" and not just "if". :-)  Fixed. LOL!

**Comment by damste** [comment]
Are you sure that the ncset() works?
? ncset(1)   &&display none
? ncset(1,.t.)  &&Display .f.
? ncset(1,.f.)  &&Display .f.

[image: Immagine in linea 1]

2015-03-15 18:46 GMT+01:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
It is a temporary regression as I finish up the SET xyz TO abc code.  I have enabled the NCSET values to also be set using the SET command, such as SET NCSETSIGNSIGN2 TO .T.|.F. as well as SET NCSETCEILINGFLOOR TO .T.|.F. ... this was done so they could be stored in the settings.

As of the last push from last night I didn't have anything working on the SET xyz TO abc except the SET DECIMAL test, which needs to examine the value to be in the range 0..18, and fail on things like SET DECIMALS TO 50. :-)

I'll get it working tonight and that regression will be fixed, and the rest of the SET xyz commands will work as well.

**Comment by RickCHodgin** [comment]
Should be working now.  See:  https://github.com/RickCHodgin/libsf/commit/f7492a8a79d6e18b8e440e18c4037f2bf8f8dc3b

**Pull request merged**
