### PR TITLE
VAL() function

### PR DESCRIPTION
**Pull request by damste**
it seems to work, let me know :-)

### CODE REVIEW

**Comment by damste** [comment]
But in VFP..."If the first character of cExpression is a dollar sign ($),*VAL(
) *returns a currency value. In all other situations *VAL( )* returns a
numeric value."
With your refactoring now val() no longer... this is right? :-)

2015-03-23 2:30 GMT+01:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
I honestly didn't know VAL() did that. :-)  I can add it in.  I just tested this in VFP9:
lnValue = VAL("$200.50")
? lnValue
* Displays  "            200.5020"

Does yours do that?  We could make ours at least be accurate. LOL :-)

**Comment by RickCHodgin** [comment]
Woah.  On repeated tests in VFP9 it produced correct results.  Freaky.

**Comment by RickCHodgin** [comment]
See:  https://github.com/RickCHodgin/libsf/commit/766ae4806d97b6816545927a2c3a9620808c3dd5

**Comment by damste** [comment]
And if is the currency symbol in ignorechars list?
See the code that I had pull yesterday

Il lunedì 23 marzo 2015, Rick C. Hodgin <notifications@github.com> ha
scritto:

**Comment by RickCHodgin** [comment]
SET CURRENCY and SET SEPARATOR symbols are automatically ignored, and if they are put into the cIgnoreChars, will be superfluous.  The SET CURRENCY value will be used as a flag.  If they want to actually ignore the currency symbol completely they can preprocess the input:

lcCurrency1 = "$200.50"
lcCurrency2 = CHRTRAN(lcCurrency1, SET("CURRENCY"), "")
VAL(lcCurrency2)

**Comment by damste** [comment]
ok, but SET CURRENCY symbol is valid only if it is prefix

? VAL("$43") && Display 43.0000   Correct
? VAL("4$3") && Display 43.0000   Correct? - VFP Display 4.00

I do not want to be controversial LOL :-)

2015-03-23 21:48 GMT+01:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
I had those thoughts as well.  I also considered the fact that I would be parsing a valid number like this:  "$$$$$$200,,,,,.50" :-)

I concluded that we should not cater to rigidity. :-)  If someone wants to use 200,,,$.50, then that's okay by me. :-)

There is actually a valid setting for SET CURRENCY which is RIGHT or LEFT (SET CURRENCY TO RIGHT) which would allow "200.50$".  So ... I am going to allow it to be anywhere, and leave it to the developer to ensure that it's not setup properly.

I've had the thought about setting flags once found, and signaling an error on the second one, or if there are not three numeric symbols between SEPARATOR symbols, etc.  It's all doable ... but how far do we want to go?

Visual FreePro, Jr. does define the ON WARNING statement (work like ON ERROR) which is designed to signal warnings which are encountered at runtime.  We could signal an ON WARNING whenever the currency symbol was not found in the first non-whitespace position, or when those other conditions occur.  The ON WARNING was designed to be a way to help developers find bugs.

What do you think?

**Comment by damste** [comment]
it is a nice idea :-)
I like the ON WARNING statement
I would say that this thing we mark, we go on with the rest of the
development, and then when we resume it later :-)

2015-03-23 22:11 GMT+01:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
Agreed.

**Pull request merged**
