### PR TITLE
PI() function

### PR DESCRIPTION
**Pull request by damste**
I tried to implement the PI() function (PI day)
how do I change "set decimals" settings?

Let me know

### CODE REVIEW

**Comment by RickCHodgin** [comment]
You can simplify it signficantly in this case because you know result was already created.  In addition, you can use a constant for pi as the ACOS() function is somewhat costly in compute time.

I think I already have _PI defined somewhere.  If not, add it to vjr_const.h along with _PI2 for pi/2, etc.  I typically carry those constants out to their full 80-bit floating point form (about 18 or 19 digits):

// vjr_const.h
const f64 _PI = 3.141592653589793238;

// commands.cpp, function_pi()
result->value.data_f64 = _PI;
return(result);

Also, in the future when bfp (big floating point) is implemented, we'll need an algorithm that can generate pi() out as far as it is defined.  I think the functions I'll use to support bfp will have that function built in as bfp_pi():

Best regards,
Rick C. Hodgin

**Comment by RickCHodgin** [comment]
There is currently no way from the command line to change the decimals value.  You could temporarily create a decimals() function which lets you change it for your testing.

If you want to work on the SET command... you could implement that as well.  I'll frame that for you later today and you can then run with the codings if you want to.

Search for the _settings object to find the definition of the current VJr settings.  However, the _settings actually operates on a stack, so you can use this in code:

WITH SET SAFETY OFF, SET CENTURY OFF, SET DELETED ON
    * Code goes here using those settings
ENDWITH

This lets the user have blocks which override specific settings here and there without the manual requirements of:
lcSafety = SET("safety")
lcCentury = SET("century")
lcDeleted = SET("deleted")

* Code goes here

SET SAFETY &lcSafety
SET CENTURY &lcCentury
SET DELETED &lcDeleted

Ugh! :-)

Best regards,
Rick C. Hodgin

**Comment by damste** [comment]
Is it correct in this way?

SVariable* function_pi(SThisCode* thisCode)
{
                SVariable* result;

result = iVariable_create(thisCode, _VAR_TYPE_F64, NULL);
*(f64*)result->value.data_f64 = (f64)_MATH_PI;  //defined in vjr_const.h

//////////
               // Return pi
//////
          return result;
}

2015-03-15 14:26 GMT+01:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
Don't forget to test the value of result.  Anything that's allocated has the potential of not being created properly, and we need to always make sure we test for that otherwise we'll get runtime errors which crash the system.  Instead, we want to catch those errors and politely handle them.

result = ...
if (!result)
{
    // Internal error

} else {
    // Assign constant
}

return result;

Best regards,
Rick C. Hodgin

**Comment by damste** [comment]
Hi Rick,
take a look at SQRT(), EXP() and PI()
Let me know

**Comment by RickCHodgin** [comment]
Can you merge them into one function? Look at the _common() functions and see how I work those.  I typically call the individual functions, but those pass through to the common function with a flag.

Search for "function_padc" and see how I pass through logical flags.  In your case, you'll pass through a numeric flag which can be examined with a switch().  Use some constants and put them in vjr_const.h, such as _FP_COMMON_EXP, _FP_COMMON_SQRT, _FP_COMMON_PI, etc.

**Comment by damste** [comment]
ok
another question...
should ceiling() and floor() functions return int value or behave like
sign() function?

2015-03-15 17:53 GMT+01:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
Yes.  I'll add an ncset() function for that, and we'll have it return integer by default.

**Comment by RickCHodgin** [comment]
Are you really whipping through these functions like this? :-)

**Comment by RickCHodgin** [comment]
We're 7,000 ?? miles away ... and collaborating like this in real time.  This is so amazing.

**Comment by RickCHodgin** [comment]
Added ncset(1) for sign/sign2, ncset(2) for ceiling/floor.

**Comment by damste** [comment]
yeah! :0)

2015-03-15 18:07 GMT+01:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
Use these to return the values for testing:

llEnabled = propGet_settings_ncset_signSign2(_settings);
llEnabled = propGet_settings_ncset_ceilingFloor(_settings);

https://github.com/RickCHodgin/libsf/commit/f377a48fdbd29088cc534d5bcd48a8210aa38d7d

**Pull request merged**
