### PR TITLE
ABS(), ACOS(), ASIN(), ATAN() and FV()

### PR DESCRIPTION
**Pull request by damste**
ABS(), ACOS(), ASIN(), ATAN() and FV() functions

### CODE REVIEW

**Comment by damste** [comment]
PV() function and minor refactoring

**Comment by damste** [comment]
at this point also I'll put the mod() inside ifunction_number_common, what
do you think? :-)

Il giovedì 19 marzo 2015, Rick C. Hodgin <notifications@github.com> ha
scritto:

**Comment by RickCHodgin** [comment]
Absolutely!  That's how it's done.  You give it your best effort, and then come in behind later with better vision and hone it down until it's in its purest form.  After all, it is far easier to edit than create. :-)

Best regards,
Rick C. Hodgin

**Comment by damste** [comment]
I agree :-)

2015-03-19 13:04 GMT+01:00 Rick C. Hodgin <notifications@github.com>:

**Pull request merged**
