### PR TITLE
vjr HOUR(), MINUTE(), SEC(), SECONDS() functions

### PR DESCRIPTION
**Pull request by damste**

### CODE REVIEW

**Comment by RickCHodgin** [comment]
I added some iTime_*() functions, and did some refactoring to honor the new SET TIME TO LOCAL|SYSTEM setting.  Local adjusts for timezone, system uses the non-timezone time.

**Comment by damste** [comment]
I'm working on SYS(2), it is very similar to seconds() (changes for
milliseconds)
In vfp however seems to give different results

? seconds(), sys(2)  && Display 47404.680, 47393

nearly 10 seconds difference :-| (no words)

Any idea?

2015-04-07 12:20 GMT+02:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
Push a commit and I'll look at the code.

**Comment by RickCHodgin** [comment]
You could wrap sys(2) around seconds(), and then use a rounding by converting to integer, then back to fp:

result = function_seconds(...)
if (result)
    result->value.data_f64 = (f64)((u64)result->value.data_f64);

That way they'd be using the same logic for calculating.

**Comment by RickCHodgin** [comment]
Make sure you claim your functions on Facebook.

**Comment by RickCHodgin** [comment]
OH!  I just saw the issue was in VFP.  Let me check.

**Comment by damste** [comment]
Exactly!! :-)

2015-04-07 13:17 GMT+02:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
I am not seeing that.  I see:
? seconds(), sys(2)
26292.617 26292

Should be 26293 anyway. :-)

**Comment by RickCHodgin** [comment]
VFP9 ?

**Comment by damste** [comment]
I just discovered that SECONDS() was a hour off in a program that had been
running for a long time. It was because we ended Daylight Savings Time last
weekend and SECONDS() didn't know because it doesn't check the clock. After
closing and reopening the application SECONDS() returned to normal.

2015-04-07 13:18 GMT+02:00 Stefano D'Amico <damicoste@gmail.com>:

**Comment by RickCHodgin** [comment]
WOW!  Interesting.

**Pull request merged**
