### PR TITLE
Between() framed

### PR DESCRIPTION
**Pull request by damste**

### CODE REVIEW

**Comment by RickCHodgin** [comment]
Is it complete?  Ready to go?  In full force?

**Comment by damste** [comment]
the function is ok, we must finish the iVariable_compare() function to test
everything correctly

2015-03-23 22:13 GMT+01:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
Working on that now.  Is a little non-trival. :-)

**Comment by damste** [comment]
In the meantime I made the OUTSIDE() function , I commit it :-)

2015-03-23 22:38 GMT+01:00 Rick C. Hodgin <notifications@github.com>:

**Pull request merged**
