### PR TITLE
vjr - ISALPHA(), ISDIGIT(), ISLOWER(), ISUPPER()

### PR DESCRIPTION
**Pull request by damste**
Hi Rick,
ISALPHA(), ISDIGIT(), ISLOWER() and ISUPPER() functions :-)

### CODE REVIEW

**Comment by RickCHodgin** [comment]
I did notice one issue, on your iscommon() for() loop through the string, you added the test varStr->data_s8[lnI] ... since we allow binary character strings, that should be a valid condition.  I realize in this case it will cause it to always fail, but I don't think we should test it as a condition in the for loop because it's testing every character atop the existing tests for data in range.

**Comment by damste** [comment]
In iscommon(), I think "llResult = true;" to be "llResult = (lnMaxLength>0);" at the beginning, otherwise an empty string will always return true...
?isalpha("")  &&return .t.  <-- I think it is not correct

**Comment by damste** [comment]
In iscommon(), I think "llResult = true;" to be "llResult =
(lnMaxLength>0);" at the beginning, otherwise an empty string will always
return true...
?isalpha("") &&return .t. <-- I think it is not correct

2015-09-19 19:52 GMT+02:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
Quite correct. Good catch.

**Pull request merged**
