### PR TITLE
vjr WEEK() function

### PR DESCRIPTION
**Pull request by damste**
My week() is different from that of vfp.
It takes three parameters: date, minimum number of days of the first week, the first day of the week.

dt = DATE ()
WEEK (dt, 1) && it is equivalent to WEEK (dt, 1) in vfp
WEEK (dt, 7) && it is equivalent to WEEK (dt, 3) in vfp
WEEK (dt, 4) && it is equivalent to WEEK (dt, 2) in vfp

I have not managed the "Regional settings"

Because right now the compile is broken I'm not aligned to your last commit

### CODE REVIEW

**Comment by RickCHodgin** [comment]
I have significantly refactored, and am still doing so. I'll have to merge this pull in manually when I get the refactoring.

**Comment by damste** [comment]
I have merged the week() function

**Comment by RickCHodgin** [comment]
Excellent. Does the refactoring make sense? Also there will be several new macros soon for simplification, like getAs_s32() which does the common code in one, etc.

**Comment by damste** [comment]
Yes, it is correct for me :-)

Il domenica 3 maggio 2015, Rick C. Hodgin <notifications@github.com> ha
scritto:

**Pull request merged**
