### PR TITLE
DTRANSFORM() untested

### PR DESCRIPTION
**Pull request by damste**
Hi Rick,
I have finished the development of DTRANSFORM(). Can you take a look at the code?
Let me know

Best regards
Stefano

Symbols:
%D  Day                   02
%B  Month                 04
%Y  Year                  2015
%H  Hour                  14
%I   Hour Am/Pm       02
%M  Minute                05
%S  Second                55
%N  Milliseconds          020
%P  AM/PM                 PM
%J  Julian                2457115
%A  Day of week           Thursday
%O  Month                 April
%T  Timestamp			  20150402140555

%d  day                   2
%b  month                 4
%y  year                  15
%h  hour                  14
%i   hour am/pm        2
%m  minute                5 
%s  second                55
%p  am/pm                 pm
%j  Day of year           92
%a  Day of week           Thu
%o  Month                 Apr
%t  Timestamp			  20150402

%%      %
%-       set mark

### CODE REVIEW

**Comment by damste** [comment]
%D  Day                   02
%B  Month                 04
%Y  Year                  2015
%H  Hour                  14
%I   Hour Am/Pm       02
%M  Minute                05
%S  Second                55
%N  Milliseconds          020
%P  AM/PM                 PM
%J  Julian                2457115
%A  Day of week           Thursday
%O  Month                 April
%T  Timestamp			  20150402140555

%d  day                   2
%b  month                 4
%y  year                  15
%h  hour                  14
%i   hour am/pm        2
%m  minute                5 
%s  second                55
%p  am/pm                 pm
%j  Day of year           92
%a  Day of week           Thu
%o  Month                 Apr
%t  Timestamp			  20150402

%%      %
%-       set mark

**Comment by RickCHodgin** [comment]
What do you mean by "untested"?

**Comment by damste** [comment]
means that I coded the function but not the I tested a lot, I just tried
the most important cases :-)

Il domenica 19 aprile 2015, Rick C. Hodgin <notifications@github.com> ha
scritto:

**Comment by RickCHodgin** [comment]
I'm going to modify the dtransform_common() function so it allocates its own buffer, returns that value, and stores the size.  I'll do this using two passes (the first to compute the actual size required in the expansion, and the second to actually do the work).

It looks good.  Minor changes overall, mostly refactoring it looks like.

I like how you converted the incoming datetimes to their equivalent SYSTEMTIME values, making every specified date also available as a datetime.  Very nice and efficient.

**Comment by damste** [comment]
After your refactoring, I will follow the refactoring of the other
functions so that they use the DTRANSFORM(), such as DTOS(), DTOC(), etc ...
What do you think about it?

2015-04-19 21:54 GMT+02:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
Yes.  I think it's an excellent idea.  The more we can tie together to a common core, the better it will be overall.

**Comment by RickCHodgin** [comment]
On %I %H and %i %h, should the output format contain "02" for %I and "02 PM" for %H, for example?  Should it actually contain the trailing " PM"?

**Comment by damste** [comment]
%H indicates the time expressed in 24h,%I the time expressed in am / pm. If
%H, hour must be expressed in 00-24, if %I 01-12. %I indicates explicitly
the time in form 01-12, %P indicates the string AM or PM.
%I and %H are the short form, 1-12 and 0-24, no zerofill.
//14:05
DTRANSFORM("%H:%M",...)  //14:05
DTRANSFORM("%h:%m",...)   //14:5
DTRANSFORM("%I:%M")       //02:05
DTRANSFORM("%i:%M %p")       //2:05 pm


Il domenica 19 aprile 2015, Rick C. Hodgin <notifications@github.com> ha
scritto:

**Comment by RickCHodgin** [comment]
Okay.  I think this is one of my all time favorite functions. :-)  I've been refactoring quite a bit and it seems to work.  Will continue testing.  Also will add in textmerge.

**Comment by RickCHodgin** [comment]
I modified it so if they don't specify any parameters, it uses the current date and time.  And if they specify a parameter beyond the ones they provided, it defaults to the current date and time as well.  I also added %L to specify whether the current SET("TIME") setting is local or system.

**Comment by RickCHodgin** [comment]
Textmerge is completed as well.  I'm going to go ahead and create a textmerge() function for that kind of arbitrary variable insertion amongst static text.

**Comment by damste** [comment]
Awesome, now it is a great function. Powerful yet simple. Hernan can use it
for his TIME() :-)

Il lunedì 20 aprile 2015, Rick C. Hodgin <notifications@github.com> ha
scritto:

**Comment by RickCHodgin** [comment]
It is my favorite XBASE function I think. It was a wonderful suggestion, Stefano. Well done.

**Comment by RickCHodgin** [comment]
I created the textmerge() function, and have added preliminary support for arbitrary left-side and right-side delimiters (instead of the default << and >>).  I'll get it working tonight (Lord willing, James 4:15). :-)  But, if you just use the regular textmerge() function with << and >>, then it is working right now (after you fix the one compiler error I purposefully introduced to draw my attention back to that line, just remove the space in "tlText Merge" and it will compile.

**Comment by damste** [comment]
We add %E for seconds elapsed since midnight. To use in SYS(2)

Il lunedì 20 aprile 2015, Rick C. Hodgin <notifications@github.com> ha
scritto:

**Comment by RickCHodgin** [comment]
Yes.  And other codes for things like "seconds this hour" and all kinds of stuff.

I think we may need to rename DTRANSFORM() to GPTRANSFORM() for "general purpose" transform, and give it a lot more abilities.  It would require almost no changes in code to give it a lot more functionality as it comes up, all available through codes which anyone can use.

We may want to consider refactoring some of the letters in use though.  I had the idea for YMD being for Year, Month, Day, and hms being for hour, minute, second, and then other ones beyond that.  That way for the original purpose it had ("date/datetime transform") those functions are all standard with the way people would think.

**Pull request merged**
