### PR TITLE
VAL() function

### PR DESCRIPTION
**Pull request by damste**
Look at this.. it is also incomplete, in _VAR_TYPE_CHARACTER case missing Currency check ($)
I will finish this...but tell me if as is done now can go :-)

### CODE REVIEW

**Comment by RickCHodgin** [comment]
Currency type is s64 / 10000 to obtain an f64.

**Comment by RickCHodgin** [comment]
lfValue = (f64)iVariable_getAs_s64(thisCode, varCurrency...) / 10000.0;
// Result is f64

**Comment by damste** [comment]
So if string starts with "$", I remove "$" character, I run strtod and then
divide the result by 10000
correct?

2015-03-22 13:56 GMT+01:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
_VAR_TYPE_CURRENCY is already a valid type, converted to s64 with an implied 4 decimals. For character, just use strtoi64(), and whatever it returns is what they get. They can use CHRTRAN() to remove characters, or VALOFS() with its parameters. But for regular VAL(), just whatever's there as is.

**Comment by RickCHodgin** [comment]
See: http://www.visual-freepro.org/wiki/index.php/Data_Operations

**Comment by RickCHodgin** [comment]
Okay, my bad. I had forgotten that by default it would skip the currency symbol without the second parameter. I can code that part, but basically copy digits one-by-one, so long as they are numeric, SET POINT or SET SEPARATOR, + or -, skipping $, or any in the ignore list, then use that value.

**Comment by damste** [comment]
I try to end up that part, I just wanted to know if what I have written so far was quite correct :-)

**Comment by RickCHodgin** [comment]
I'll merge the pull, apply and changes, and re-push.  Give me a few...

**Comment by damste** [comment]
I did made refactoring of VAL, now ignore char and test currency, missing
set point check
I will finish it this night

2015-03-22 15:04 GMT+01:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
I have some significant refactoring as well.  I added a feature for iVariable_getAs_s32() for _VAR_TYPE_LOGICAL, that if you use forced conversion, it will return 0 or 1 instead of 0 or -1.  BTW, the reason why it is -1 is because that is all of the bits set to 1 for .T., and for false it is all of the bits set to 0.

**Comment by RickCHodgin** [comment]
It's in there... let me know.

See:
https://github.com/RickCHodgin/libsf/commit/930a75a612dd41b693c1c8394c54ab7a3fe62bde

**Comment by RickCHodgin** [comment]
And a second push for SET POINT and SET SEPARATOR.  Use this to make it faster:

s8 lcCurrency, lcPoint, lcSepartor;

lcCurrency = varCurrency->value.data_s8[0];
lcPoint = varPoint->value.data_s8[0];
lcSeparator = varSeparator->value.data_s8[0];

**Pull request merged**
