### PR TITLE
CTOT() and CTOT()

### PR DESCRIPTION
**Pull request by damste**

### CODE REVIEW

**Comment by RickCHodgin** [comment]
Rejected.  Please refactor as per the example I gave which uses the already assembled system-formatted date or datetime for the pattern.  By using that methodology, we can add additional date formats and only have to update the one algorithm.

**Comment by damste** [comment]
CTOT and CTOD in vfp are much more flexible. Accept any date separator
between -. / regardless of the date mark, the year can be expressed as YY
yyyy indiscriminately, accept XML, SQL, ACCESS, etc ...date format.Do we
follow this path, or accept only formatted strings so very strict?
Let me know

Il sabato 11 aprile 2015, Rick C. Hodgin <notifications@github.com> ha
scritto:

**Comment by damste** [comment]
I would like to perform a refactoring of
iVariable_convertForDisplay() function  for cases date and datetime.
I would use the formatted strings to get the result, something like ..
year = 2015;
month = 5;
day = 15;
s8 format [] = vjr_getDateFormat(); // "%D-%B-%Y"
dateStr = iVariable_datetime_format (format, year, month, day, hour,
minute, second, millisecond);

dateStr contain "15-05-2015"

s8 format [] = "%d-%b-%y"   //short
dateStr = iVariable_datetime_format (format, year, month, day, hour,
minute, second, millisecond);

dateStr contain "15-5-15"

It will work like the sprintf (...)

The usual string format will be used by CTOT () and CTOD () to do
otherwise. So if we change the formatting string (vjr_getDateFormat), the
functions will no longer be changed.
What do you think about it? :-)

Apr.02.2015 14:05:55.020

//Long
%D  Day             DD      02
%B  Month           BB      04
%Y  Year            YYYY    2015
%H  Hour            HH      14      02 If %P is in string
%M  Minute          MM      05
%S  Second          SS      55
%N  Milliseconds    NNN     020
%P  AM/PM                   PM
%J  Julian                  2457115
%A  Day of week             Thursday
%O  Month                   April

//Short
%d  day             dd      2
%b  month           bb      4
%y  year            yy      15
%h  hour            hh      14      2 If %P is in string
%m  minute          mm      5
%s  second          ss      55
%p  am/pm                   pm
%j  Day of year             92
%a  Day of week             Thu
%o  Month                   Apr

Example:
In
"%A, %d %o. %H:%M:%S"
Out
"Thursday, 2 Apr. 14:05:55"
In
"%P%o.%D.%Y %H:%M:%S.%N"
Out
"Apr.02.2015 02:05:55 PM"

2015-04-12 8:39 GMT+02:00 Stefano D'Amico <damicoste@gmail.com>:

**Comment by damste** [comment]
sorry, last example is wrong
In
"%o.%D.%Y %H:%M:%S.%N %P"
Out
"Apr.02.2015 02:05:55.020 PM"


2015-04-12 14:32 GMT+02:00 Stefano D'Amico <damicoste@gmail.com>:

**Comment by RickCHodgin** [comment]
#1 -- SET STRICTDATE and StrictDateEntry also hep determine how fixed or flexible it is for normal date inputs.  In the cases of the default strict value of 1, the date separator character will be known by retrieving SET("MARK"), and if encountered from our system-derived sample (which will have used the default-for-the-type or SET MARK character), can then be tested for any of the legal values, including the value of SET("MARK") itself (because it's possible the user set it to some non-standard value and is using that).  Creating a cMark value, and using that for our test would do it.

In cases of the explicit "2015-04-12THH:MM:SS.Mss" formats, the positions of the "-" and ":" characters can be tested at start, and if found use the proper system-generated date in that format (ones that will have been created by a trigger on changes to  SET CENTURY or SET MARK).

#2 -- Expose the new general purpose date formatting as a new TRANSFORM() ability, or introduce a new function (like TRANSFORM2() or TRANS2()) to handle all % format characters.  Create a new ifunction_trans2_common().  We can use that function internally to render the dates.

Make sure that ifunction_trans2_common() code receives and populates an s8* buffer (and not an SVariable), that way we can use it internally everywhere as well.

**Comment by damste** [comment]
I'll try :-)

2015-04-12 15:06 GMT+02:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
I've been thinking that DTRANSFORM() would be a good name for this function.  It would allow a one or many dates/datetimes to be provided, along with other variables, and then the references to each could provided with a prefixing number.  Something like %1 and %2 prefixing the actual code, and then pulling from the appropriate value:

```javascript
lcResult = DTRANSFORM("%1A, %1d %1o. %2H:%2M:%2S", ldDateNextVisit, ltDatetimeLastAppointment)
* %A, %d, %o are pulled from ldDateNextVisit
* %H, %M, %S are pulled from ltDatetimeLastAppointment

lcResult = DTRANSFORM("%A, %d %o. %2H:%2M:%2S", ldDateNextVisit, ltDatetimeLastAppointment)
* %A, %d, %o are pulled from ldDateNextVisit by default
* %H, %M, %S are pulled from ltDatetimeLastAppointment

lcResult = DTRANSFORM("%A, %d %o. %H:%M:%S", ltDatetimeNextVisit)
* Everything is pulled from ldDatetimeNextVisit by default
```

We could also then provide PRINTF() as a wrapper to sprintf(), to use the actual C function and its abilities, providing the translation between passed parameters and their internal requirements.

What do you think?  I would be willing to code PRINTF() and DTRANSFORM() if you'd like.

Best regards,
Rick C. Hodgin

**Comment by damste** [comment]
I like DTRANSFORM(), but it should allow one date/datetime. Will always be
possible to concatenate two DTRANSFORM()

lcResult = DTRANSFORM("%A, %d %o. ", ldDateNextVisit) +
DTRANSFORM("%2H:%2M:%2S", ltDatetimeLastAppointment)

I would not want it to become too complex. :-)



2015-04-13 17:50 GMT+02:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
It shouldn't be hard.  Just parse the first character after the %:

```javascript
/////////
// Examine the character after %:
//////
    c = varFormat->value[lnI];
    if (c >= '0' and <= '9')  lnIndex = (s32)(varFormat->value[lnI] - '0');
    else                      lnIndex = 0;


//////////
// Use the indicated date
//////
    varDate = returnsParams->params[lnIndex];
    if (varDate == NULL)
    	// Report error and exit

    // When we get here, varDate is now pointing to the proper date
```

Best regards,
Rick C. Hodgin

**Comment by damste** [comment]
I said not complicated to make but to use :-)
Transform()  takes one parameter only...that's all :-)

2015-04-13 18:59 GMT+02:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
Limiting this ability is an unnecessary hobbling of the functionality of DTRANSFORM().

If the user only wants to use a single date parameter, then they are free to do so.

For the more advanced user who wants to use two or more date parameters, then they can also do so as well if this ability exists.  And since it isn't that much more difficult to code, why leave it out?

Best regards,
Rick C. Hodgin

**Comment by damste** [comment]
OK, you've convinced me :-D

2015-04-13 19:04 GMT+02:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
Good.  I was about to write, "I appreciate your input, Stefano, but if this is your firm position ... then I'll go back to coding VJr alone."

So you can understand clearly where I'm coming from:

I have a particular vision about the features I want to provide people, including myself.  I'm not trying to create a copy of another tool which already exists, or even an extended version of a tool which already exists.  God has given me a particular set of developer abilities, and a way of looking at things, and I have been applying His guidance in my life on this project first and foremost.

The full version of Visual FreePro introduced in its design a new virtual machine, one that is similar to Java or .NET, but different in that it has a host of new software abilities that I've never seen or heard of before.  Many of them are documented on my wiki (PURSUEs are the biggest, but also form mashing, and the ability to switch between 2D and 3D presentation modes).

And beyond that, I am not writing this project for popularity, or money, or to cater to other people's whims.  It is an effort of love, a culmination of the varied skills God first gave me, that I am returning to Him, using them for Him as He gave them to me (freely), trying to create the fullest vision of that which He placed upon my heart.  And to get here I have had no end of resistance and rebellion.  I've been kicked off of Visual FoxPro developer boards for preaching about Jesus Christ in the midst of my normal posts, as the comments about who we are, what we are supposed to be doing int his world, and why we are supposed to be doing it (for God, for Jesus, for each other) run contrary to that which people want to hear.  It has literally been me developing this unto God, with Hernan being there for support all along.  It has been a wonderful experience, but from a worldly perspective, it has seemed different.

I hope this makes sense to you through translation.  I was 969 days working on this project alone by myself (longer if you consider the initial plans I had back before that in first developing Visual FreePro shortly after Microsoft announced its cancellation).  And I am truly more than happy to continue working on it alone if doing so means it's the only way the vision He gave me will getout, and if having assistance means receiving advice which suggests I step away from the vision I've been working on, and move in another direction.

I recognize there are skills and abilities in other people which will come with them when they arrive at the project, and many of these will inherently change the product.  But some fundamental principles like this (the idea of removing functionality because some users might find it too complex) are immutable in my book.  I will not be swayed in these areas, and as much as it might hurt me to return back to coding my project alone (hurt me personally, as I desire greatly to have help from people), I would do so to maintain that vision, using the full skill set God gave me.

I hope this makes sense through translation.

Best regards,
Rick C. Hodgin

**Comment by damste** [comment]
it makes perfect sense, I did not want to criticize your ideas but only
express my opinion. this does not mean that things have to be done the way
I want. I find your ideas very bright. the idea to simplify and make things
simple is just my way of working. in Italian 'deviazione professionale' :-)
Because my work :-)

Il lunedì 13 aprile 2015, Rick C. Hodgin <notifications@github.com> ha
scritto:

**Comment by RickCHodgin** [comment]
Understood.  And please know I appreciate your developer abilities and input very much.  You have been a great blessing to the project, and you have helped and aided me in many areas.

Best regards,
Rick C. Hodgin

**Comment by RickCHodgin** [comment]
See:  http://www.visual-freepro.org/wiki/index.php/VXB#DTRANSFORM.28.29

**Comment by damste** [comment]
I would add...
%T    Timestamp              20150402140555
%t    Timestamp  (DTOS)      20150402

in this way...

DTOS(...)           ->  DTRANSFORM("%t", ...)
TTOS(...) (new?)    ->  DTRANSFORM("%T", ...)
TTOC(...)           ->  DTRANSFORM([format SET(DATE)], ...)
DTOC(...)           ->  DTRANSFORM([format SET(DATE)], ...)
CDOW(...)           ->  DTRANSFORM("%A", ...)
CMONTH(...)         ->  DTRANSFORM("%O", ...)
DMY(...)            ->  DTRANSFORM("%D %O %Y", ...) or DTRANSFORM("%D %O
%y", ...)  [format SET(CENTURY)]
MDY(...)            ->  DTRANSFORM("%O %D, %Y", ...) or DTRANSFORM("%O %D,
%y", ...)  [format SET(CENTURY)]
SYS(1)              ->  DTRANSFORM("%J", DATE())
SYS(11, ...)        ->  DTRANSFORM("%J", ...)
SYS(10, ...)        ->  DTRANSFORM([format SET(DATE)], ...)
TIME(...)           ->  DTRANSFORM("%H:%M:%S %P", DATETIME()) or
DTRANSFORM("%H:%M:%S.%N",
DATETIME())  [format by SET(HOUR) && ...]

:-)

2015-04-14 3:20 GMT+02:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
Sounds excellent.

**Pull request closed without merging**
