### PR TITLE
DTOT(), TTOD() and TTOC()

### PR DESCRIPTION
**Pull request by damste**
// TODO:  We need to honor the SET DATE settings.  For now we use MM/DD/YYYY HH:MM:SS.Mss AM

### CODE REVIEW

**Comment by damste** [comment]
SYS(1), SYS(2), SYS(10) added

**Comment by RickCHodgin** [comment]
Will check the code later tonight (about 10 hours from now).  Thank you, Stefano.

**Comment by RickCHodgin** [comment]
Looks good initially, Stefano. :-)

**Comment by RickCHodgin** [comment]
I added a new feature on DTOT() which allows an optional second parameter that will populate with the number of seconds, to have the time be something other than midnight.  Also some debugging to validate ranges, and minor refactoring to simplify assignment and/or logic.

A good submission, Stefano.  You are learning the system very quickly.

See:  https://github.com/RickCHodgin/libsf/commit/a31d902bed3dba635beec5e13e1351f1fa00455c

**Comment by RickCHodgin** [comment]
Search for "result->varType == _VAR_TYPE_F64" to see the simplified assignment (since both f64 and s64 are already 8-bytes, you can directly interchange between them by casting f64 to s64, and then changing the varType to indicate its new form.

**Comment by RickCHodgin** [comment]
A nice feature woul be to allow "Hh:Mm:Ss.Mss" as character. :-)

**Comment by damste** [comment]
Yes I like..
a part of ctot () may be recycled for this part

2015-04-09 10:50 GMT+02:00, Rick C. Hodgin <notifications@github.com>:

**Comment by damste** [comment]
Any ideas on how to implement CTOD() and CTOT() functions?

I was thinking of something like this ...

//////////
//
// Computes the day, month, and year from a character expression.
//
// Returns:
// year -- The year
// month -- The month
// day -- The day
//
//////
void iiVariable_extract_YyyyMmDd_from_string(SThisCode* thisCode, u8*
tcStr, u32* year, u32* month, u32* day)
{
u32 lnBuffOffset, lnToken;
s32 lnI, lnNum[3] = { -1, -1, -1};
s8 buffer[8], c;

//////////
// Iterate through each character
//////
for (lnI = 0, lnToken = 0, lnBuffOffset = 0; lnToken < 3 && lnI <
(s32)strlen(tcStr) && lnBuffOffset < (s32)sizeof(buffer) - 1; lnI++)
{

//////////
// Grab this character
//////
c = tcStr[lnI];


//////////
// Is it a number?
//////
if (c >= '0' && c <= '9')
{
// Yes, Copy this character
buffer[lnBuffOffset++] = c;
} else {
// Are we still in a valid sequence of characters to skip?
if (c == ' ')
{
// It's a character we're skipping naturally (space, separator symbol)
// We don't do anything here ... it's just more clear to keep this logic
visible rather than inverting it. :-)

} else if (c == '-' || c == '.' || c == '/') {
// We encountered the date delimiter

// NULL terminate
buffer[lnBuffOffset] = 0;
lnNum[lnToken++] = (u32)atoi(buffer);

// Reset
lnBuffOffset = 0;

} else if (lnToken == 2){
// We're done

// NULL terminate
buffer[lnBuffOffset] = 0;
lnNum[lnToken++] = (u32)atoi(buffer);
 break;
}
}

}

// Prepare for our year
/*if (propGet_settings_Century(_settings)) lnYearOffset = 0;
else lnYearOffset = 2;*/

//Have we found all tokens?
if (lnToken == 3)
{
// Based on type, convert
switch (propGet_settings_Date(_settings))
{
case _SET_DATE_MDY:
case _SET_DATE_AMERICAN: // mm/dd/yy
case _SET_DATE_USA: // mm-dd-yy
case _SET_DATE_LONG: // Dayofweek, Month dd, yyyy
case _SET_DATE_SHORT: // m/d/yy
// Month
*month = lnNum[0];

// Day
*day = lnNum[1];

// Year
*year = lnNum[2];
break;

case _SET_DATE_ANSI: // yy.mm.dd
case _SET_DATE_TAIWAN: // yy/mm/dd
case _SET_DATE_YMD: // yy/mm/dd
case _SET_DATE_JAPAN: // yy/mm/dd
// Month
*month = lnNum[1];

// Day
*day = lnNum[2];

// Year
*year = lnNum[0];
break;

case _SET_DATE_BRITISH: // dd/mm/yy
case _SET_DATE_FRENCH: // dd/mm/yy
case _SET_DATE_DMY: // dd/mm/yy
case _SET_DATE_GERMAN: // dd.mm.yy
case _SET_DATE_ITALIAN: // dd-mm-yy
// Month
*month = lnNum[1];

// Day
*day = lnNum[0];

// Year
*year = lnNum[2];
break;
}

//TODO -- Rollover
if (*year >= 65 && *year <= 99)
*year += 1900;
else if (*year >= 0 && *year <= 64)
*year += 2000;
}
}

Let me know...


2015-04-09 11:19 GMT+02:00 Stefano D'Amico <damicoste@gmail.com>:

**Comment by RickCHodgin** [comment]
If it's not SHORT, then I would create a date or datetime variable and populate it with known constant values, like:
var1 = iVariable_create(thisCode, _VAR_TYPE_DATE, ...);
iiVariable_convertTo_YYYYMMDD_from_YyyyMmDd(var1->value.data, 3333, 11, 22);
var2 = iVariable_convertForDisplay(thisCode, var1);

You've (1) used the current system settings to prepare the date into the proper system form, so now you (2) know that where the 11 is for the month portion, the 22 is for the day portion, the 3333 is for the year portion (or 33 if century is off).  And you can extend this out for the datetime:  11/22/3333 44:55:00.123.

In this way, you can parse the string looking for non-numbers, and determine if the format is correct (if they use / or - where they should, if there is : and . where it should be, etc).  You can verify that those character are correct, and note the start of each component while doing that, and then extract.

If SHORT, you will have to parse the input differently because its length will vary, but that will then always be procedural:  Name of month, day of month, year, and then time.

Make sense?

Best regards,
Rick C. Hodgin

**Comment by RickCHodgin** [comment]
Time portion should be 12:34:56.789, but you'll probably need to use another value for 789 because milliseconds can't be stored exactly.  It only has enough precision to round to the nearest 3rd or 4th millisecond depending on value.  You could use .000 and that would work.

**Comment by damste** [comment]
May be sufficient to have a parser in fixed positions?
I'll explain ...
SET DATE ITALIAN
CTOD ("25/11/1978") && returns a date value Nov.25.1978

Parser string "25/11/1978"
num [1] = substring from start to index 2
num [2] = substring from index 3 to index 5
num [2] = substring from index 6 to end

strings like "25 /  11  /  1978  " will not be accepted... the parser would
be very strict

Or is it better to do a parser more like that of VFP that eliminates the
spaces?

2015-04-10 17:59 GMT+02:00 Rick C. Hodgin <notifications@github.com>:

**Comment by RickCHodgin** [comment]
By creating the date with the known values for constants, the input and our known constant can be parsed together:

if (var1->value.length != varCtodString->value.length)
    // Formatting error

for (lnI = 0; lnI < var1->value.length; lnI++)
{
    switch (var1->value.data[lnI])
    {
        case '1':  // Either 11 or 12, for MM or Hh
            if (var1->value.data[lnI + 1]) == '1')    // Is MM
            else   // Is Hh

        case '2':  // Dd
        case '3':  // Either 33/3333 or 34, for YY/YYYY or Mm
            if (var1->value.data[lnI + 1] == '3')    // Is YY/YYYY
            else    // Is Mm

        case '5':  // Ss
        case '0':  // Mss
        default:
            if (var1->value.data[lnI] != varCtodString->value.data[lnI])
                // Input syntax formatting error
    }
}

By iterating through, we don't need to worry about any peculiarities for any date form, we just match up the input with what would be generated by our system using the current DATE, CENTURY, and TIME settings, and go with whatever we get.  At the start of each of those locations, store the offset and then you can use atoi() to extract its value, and it will be automatically terminated by the invalid character which comes after it.

Best regards,
Rick C. Hodgin

**Pull request merged**
