### PR TITLE
FORCEEXT(), FORCEPATH(), FORCEFNAME(), FORCESTEM()

### PR DESCRIPTION
**Pull request by damste**

### CODE REVIEW

**Comment by RickCHodgin** [comment]
Awesome! :-)  A couple notes:

Regarding:
result = iVariable_create(thisCode, _VAR_TYPE_CHARACTER, NULL, true);

(1) Need to check to make sure result was created properly in each function.  Should use error and errorNum.  Also, (2) rename the ifunction_parser_pathname() function to ifunction_pathname_common().

Best regards,
Rick C. Hodgin

**Comment by damste** [comment]
Ok, I will check all functions :-)

Il lunedì 30 marzo 2015, Rick C. Hodgin <notifications@github.com> ha
scritto:

**Comment by damste** [comment]
I did it, please check this :-)

**Comment by RickCHodgin** [comment]
Will check it out and merge it tomorrow.  Sorry for the delay.  I've been doing a lot of event refactoring, and adding support for carousels and riders.

**Comment by damste** [comment]
well done! :-)
I do a little test, but I'm sure they work :-)

**Pull request merged**
